export * from './CovidContent/CovidDataFiles'
export * from './CovidContent/StaticCovidData'
export * from './CovidContent/StaticCovidDataItem'
export * from './DataContent/CollapseMSDeath_data'
export * from './DataContent/CollapseParamAltay'
export * from './DataContent/CollapseParamAltaysmoothed'
export * from './DataContent/CollapseParamCSV'
export * from './DataContent/CollapseParamInvitro'
export * from './DataContent/CollapseParamNSKsmall'
export * from './DataContent/CollapseParamOmsk'
export * from './Footer/Footer'
export * from './MainContent/ConferenseItem'
export * from './MainContent/MCinfo'
export * from './MainContent/MPInfo'
export * from './MainContent/MPitem'
export * from './MainContent/Main_conferences'
export * from './MainContent/Main_contacts'
export * from './MainContent/Main_picture'
export * from './MainContent/Main_publications'
export * from './MainContent/TeamItem' //

export * from './ModelsDescription/Description_AOM'
export * from './ModelsDescription/Description_SEIRHCD'

export * from './NavBar/NaviBar'
export * from './NavBar/NaviBarv2'
